### ISSUE TITLE
Failed to build or run the app

### ISSUE THREAD

**Issue by sliontc** [qianzhaoy/vant--mobile-mall#16]
Failed to compile.

./src/core/async-loader.js
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'range' of null
    at OffsetStorage.setDesiredOffset (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\rules\indent.js:335:45)
    at C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\rules\indent.js:1310:29
    at Array.forEach (<anonymous>)
    at Object.TemplateLiteral [as listener] (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\rules\indent.js:1304:34)
    at C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\rules\indent.js:1496:55
    at Array.forEach (<anonymous>)
    at Program:exit (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\rules\indent.js:1496:26)
    at C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\linter.js:868:28)
    at Traverser._traverse (C:\Users\Administrator\Downloads\vant--mobile-mall-dev\node_modules\eslint\lib\util\traverser.js:155:18)

**Comment by chana1024** [comment]
change 'import(`@/views/${chunkPath}`)' to 'require(`@/views/${chunkPath}`)' in async-loader.js
https://blog.csdn.net/weixin_42406046/article/details/103718293
